### PR TITLE
My enumerable

### PR DESCRIPTION
**Pull request by saied2035**
### Project requirements
- We created a class `MyList` that has an instance variable `@list`. ✔️ 
- In `MyList`, We implemented a method `each` that yields successive members of `@list` and uses the `MyEnumerable` module. ✔️ 
- we created a module `MyEnumerable` that implements the following methods (they have the same functionality as methods in [Enumerable](https://ruby-doc.org/core-3.0.0/Enumerable.html)):
  - `all?` ✔️
  - `any?` ✔️
  - `filter` ✔️
- Each class and module has a separate .rb file. ✔️
-  We verified our solution. ✔️

Thanks for reviewing our PR. 😄

### CODE REVIEW

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
```markdown
Hi team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not follow GitHub flow. Please learn more about GitHub flow [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

Invalid Code Review Request **does not count** into the code reviews limit._
```

**Comment by iLynette** [comment]
Hi, @SajjadAhmad14 Thank you for the review but my partner and I think we have followed gitflow. Could you be kind enough to tell us exactly what we are missing/doing wrong?

**Comment by SajjadAhmad14** [comment]
Hi @iLynette, you should have followed GitHub flow. The default branch should be `master/main` and open a PR from `feature` to `master/main`.

**Comment by iLynette** [comment]
Thank you @SajjadAhmad14 we have changed the base branch, thank you.

**Review by hiromataba — APPROVED** [review]
# Status: Approved :tada: :tada: :tada: 
Hi @saied2035 and @iLynette     :wave: :wave: 

200w  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by iLynette** [comment]
Thank you for the review @hiromataba

**Comment by hiromataba** [comment]
You are welcome @iLynette

**Pull request merged**
